import "./globals.css";

import type {Metadata} from "next";
import {hasLocale, NextIntlClientProvider, useLocale} from "next-intl";
import {Geist, Geist_Mono, Noto_Sans_Display} from "next/font/google";
import Head from "next/head";
import {Toaster} from "sonner";

import arMessages from "../messages/ar.json";
import enMessages from "../messages/en.json";
import {notFound} from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const notoSans = Noto_Sans_Display({
  subsets: ["latin"],
  variable: "--font-noto-sans-display",
  weight: ["400", "500", "600", "700", "800"], // Add font weights as needed
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const messages: Record<string, any> = {
  en: enMessages,
  ar: arMessages,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale: string = useLocale();

  if (!hasLocale(["en", "ar"], locale)) {
    notFound();
  }
console.log('locan current',locale);

  return (
    <NextIntlClientProvider locale={locale} messages={messages[locale]}>
      <html lang={locale}>
        <Head>
          <link
            href="https://fonts.googleapis.com/css2?family=Noto+Sans+Display:wght@400;700&display=swap"
            rel="stylesheet"
          />
        </Head>
        <body
          className={`${notoSans.variable} ${geistSans.variable} ${geistMono.variable} antialiased text-deep-blue-gray`}
        >
          <Toaster />
          {children}
        </body>
      </html>
    </NextIntlClientProvider>
  );
}
