import {
  AppWindow,
  ChartLine,
  ChartNoAxesCombined,
  Check,
  ChevronDown,
  ChevronUp,
  Clock8,
  HandHelping,
  Home,
  Link,
  LockKeyholeOpen,
  LogOut,
  Paintbrush,
  ScanLine,
  Settings,
  Sparkle,
  Sparkles,
  Star,
  User,
  X,
  CircleCheckBig,
} from "lucide-react";

const icons = {
  link: Link,
  star: Star,
  appWindow: AppWindow,
  clock8: Clock8,
  handHelping: HandHelping,
  check: Check,
  x: X,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  user: User,
  home: Home,
  paintbrush: Paintbrush,
  settings: Settings,
  "chart-no-axes-combined": ChartNoAxesCombined,
  "chart-line": ChartLine,
  "scan-line": ScanLine,
  sparkle: Sparkle,
  sparkles: Sparkles,
  "lock-keyhole-open": LockKeyholeOpen,
  "log-out": LogOut,
  "circle-check-big":CircleCheckBig,
};

export type iconNameType = keyof typeof icons;
export default icons;
