import {
  AppWindow,
  ChartLine,
  ChartNoAxesCombined,
  ChartSpline,
  Check,
  ChevronDown,
  ChevronUp,
  CircleHelp,
  Clock8,
  HandHelping,
  Home,
  Link,
  Lock,
  LockKeyholeOpen,
  LogOut,
  Paintbrush,
  Podcast,
  QrCode,
  ScanLine,
  Settings,
  Sparkle,
  Sparkles,
  Star,
  User,
  X,
} from "lucide-react";

import {
  SiFacebook,
  SiInstagram,
  SiLinkerd,
  SiGithub,
  SiReddit,
  SiX,
  SiDiscord,
  SiTiktok,
  SiPinterest,
   SiYoutube,
  SiVimeo,
  SiSnapchat,
  SiMedium,
  SiSpotify,
  SiTelegram,
  SiDribbble,
  SiBehance,
  SiTwitch,
  SiApplemusic,
  SiSteam,
  SiSoundcloud,
  // SiYoutubemusicpodcast,
  SiPatreon,
  // SiOnlyFans,
  // SiKoFi,
  SiAmazon,
  SiMeetup,
   SiLastdotfm,
  // Six,
  SiTumblr,
  // SiCaffeine,
  SiClubhouse,
  SiBluesky,
  SiTidal,
  SiSlack,
} from "@icons-pack/react-simple-icons";

const socialIcons = {
  facebook: SiFacebook,
  instagram: SiInstagram,
  // linkedin: SiLinkedin,
  github: SiGithub,
  reddit: SiReddit,
  twitter: SiX,
  discord: SiDiscord,
  tiktok: SiTiktok,
  pinterest: SiPinterest,
  youtube: SiYoutube,
  vimeo: SiVimeo,
  snapchat: SiSnapchat,
  medium: SiMedium,
  spotify: SiSpotify,
  telegram: SiTelegram,
  dribbble: SiDribbble,
  behance: SiBehance,
  twitch: SiTwitch,
  applemusic: SiApplemusic,
  steam: SiSteam,
  soundcloud: SiSoundcloud,
  googlepodcasts: Podcast,
  patreon: SiPatreon,
  // onlyfans: SiOnlyFans,
  // kofi: SiKoFi,
  amazon: SiAmazon,
  meetup: SiMeetup,
  lastfm: SiLastdotfm,
  slack: SiSlack,
  tumblr: SiTumblr,
  // caffeine: SiCaffeine,
  clubhouse: SiClubhouse,
  bluesky: SiBluesky,
  tidal: SiTidal,
};

const icons = {
  link: Link,
  star: Star,
  appWindow: AppWindow,
  clock8: Clock8,
  handHelping: HandHelping,
  check: Check,
  x: X,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  user: User,
  home: Home,
  paintbrush: Paintbrush,
  settings: Settings,
  "chart-no-axes-combined": ChartNoAxesCombined,
  "chart-line": ChartLine,
  "chart-spline": ChartSpline,
  "scan-line": ScanLine,
  "qr-code": QrCode,
  sparkle: Sparkle,
  sparkles: Sparkles,
  "lock-keyhole-open": LockKeyholeOpen,
  lock: Lock,
  "log-out": LogOut,
  "circle-help": CircleHelp,
  ...socialIcons,
};

export type iconNameType = keyof typeof icons;
export default icons;
